version: '3.8'

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: P@ssw0rd123!
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1433:1433"